"use client";
import { useState } from "react";
import { createLab, submitLurynWrite, type LurynWrite } from "@/lib/genlayer/writes";
const actions: LurynWrite[] = ["set_source_manifest", "set_defender", "register_decoy", "set_decoy_active", "submit_interaction", "classify_interaction", "group_pattern", "set_finding_status", "record_mitigation", "publish_sanitized_lesson"];
export function LabLauncher() {
  const [address, setAddress] = useState<`0x${string}` | null>(null); const [name, setName] = useState("Luryn testnet lab"); const [status, setStatus] = useState("Ready"); const [action, setAction] = useState<LurynWrite>("set_source_manifest"); const [args, setArgs] = useState('[1, "[{\\"source_type\\":\\"CONTEXT\\",\\"url\\":\\"https://docs.genlayer.com/full-documentation.txt\\"}]"]');
  async function connect() { try { if (!window.ethereum) throw new Error("Install or enable an injected EIP-1193 wallet."); const accounts = await window.ethereum.request({ method: "eth_requestAccounts" }) as string[]; if (!accounts[0]) throw new Error("Wallet did not return an account."); setAddress(accounts[0] as `0x${string}`); setStatus("Wallet connected. StudioNet is requested only on submission."); } catch (error) { setStatus(error instanceof Error ? error.message : "Wallet connection failed."); } }
  async function submit() { if (!address) return connect(); try { setStatus("Signature requested…"); const result = await createLab(address, name, "PRIVATE"); setStatus(`Finalized create_lab: ${result.hash}`); } catch (error) { setStatus(error instanceof Error ? error.message : "Lab submission failed."); } }
  async function submitAction() { if (!address) return connect(); try { const parsed: unknown = JSON.parse(args); if (!Array.isArray(parsed)) throw new Error("Arguments must be a JSON array."); setStatus("Signature requested…"); const result = await submitLurynWrite(address, action, parsed); setStatus(`Finalized ${action}: ${result.hash}`); } catch (error) { setStatus(error instanceof Error ? error.message : "Transaction failed."); } }
  return <section className="field-card" aria-label="Luryn contract actions"><span className="status">{address ? "Wallet connected" : "Wallet not connected"}</span><h2>Begin a real lab</h2><p>Creates an on-chain private testnet lab. No wallet connection occurs until you choose it.</p><label className="mono" htmlFor="lab-name">Lab name</label><input id="lab-name" value={name} maxLength={80} onChange={(event) => setName(event.target.value)} /><div className="actions"><button className="button alt" onClick={connect}>{address ? "Wallet connected" : "Connect wallet"}</button><button className="button" onClick={submit}>{address ? "Create lab on StudioNet" : "Connect to continue"}</button></div><hr /><h3>Verified lifecycle writer</h3><p className="mono">Each submission waits for FINALIZED and rejects a finalized transaction whose leader execution failed.</p><label className="mono" htmlFor="contract-action">Contract action</label><select id="contract-action" value={action} onChange={(event) => setAction(event.target.value as LurynWrite)}>{actions.map((item) => <option key={item}>{item}</option>)}</select><label className="mono" htmlFor="contract-args">JSON arguments (must match the deployed schema)</label><textarea id="contract-args" value={args} onChange={(event) => setArgs(event.target.value)} rows={4} /><div className="actions"><button className="button" onClick={submitAction}>Submit real transaction</button></div><p className="mono" role="status">{status}</p></section>;
}
